name: Test SDK UI Logic
on: [push]

concurrency:
  group: ${{ github.ref }}-ui
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    env:
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          # restore and save a cache using this key
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          # if there's no cache hit, restore a cache by this prefix
          restore-prefixes-first-match: nix-${{ runner.os }}-
          # collect garbage until the Nix store size (in bytes) is at most this number
          # before trying to save a new cache
          # 1G = 1073741824
          gc-max-store-size-linux: 1G

      - run: nix develop -c build-submodules

      - run: nix develop -c local-bundle

      - name: Install Playwright browsers with dependencies
        run: |
          cd svelte-test
          npx playwright install --with-deps

      - run: nix develop -c test-ui

      - name: Frontend linting and formatting
        run: |
          cd svelte-test
          npm run lint-format-check